baseURL: "https://nathanchance.dev/"
enableRobotsTXT: true
pygmentsUseClasses: true
theme: PaperMod
title: "Nathan Chancellor"

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - name: Blog
    url: posts/
    weight: 1
  - name: About
    url: about/
    weight: 2
  - name: Resume
    url: nc_resume.pdf
    weight: 3
  - name: Downloads
    url: downloads/
    weight: 4

minify:
  disableXML: true

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  author: Nathan Chancellor
  comments: true
  defaultTheme: auto
  env: production
  social: true

  editPost:
    URL: "https://github.com/nathanchance/hugo-files/blob/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  homeInfoParams:
    Title: "Hello 👋"
    Content: >
      I am a Linux kernel developer focused on improving compatibility with LLVM and clang as part of [ClangBuiltLinux](https://clangbuiltlinux.github.io/). I mostly blog about my work and tips and tricks that I discover.

  socialIcons:
    # personal / site
    - name: rss
      url: "/index.xml"
    - name: email
      url: "mailto:nathan@kernel.org"
    - name: cv
      url: "/nc_resume.pdf"
    - name: other
      url: "/99739260CB6CB716.asc"
    # social
    - name: mastodon
      url: "https://hachyderm.io/@nathanchance"
    - name: pixelfed
      url: "https://pixelfed.social/@nathanchance"
    - name: bluesky
      url: "https://bsky.app/profile/nathanchance.bsky.social"
    - name: linkedin
      url: "https://linkedin.com/in/nathanchancellor"
    # git
    - name: github
      url: "https://github.com/nathanchance"
    - name: forgejo
      url: "https://codeberg.org/nathanchance"
    - name: gitlab
      url: "https://gitlab.com/nathanchance"
    # chat
    - name: telegram
      url: "https://t.me/nathanchance"
    # forums
    - name: xda
      url: "https://forum.xda-developers.com/m/nathanchance.6842057/"
    # video
    - name: twitch
      url: "https://twitch.tv/nathanchance"
    - name: youtube
      url: "https://www.youtube.com/user/NateChs"

  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowToc: true
