# Universal configuration
baseurl = "https://nathanchance.dev/"
disqusShortname = "nathanchance"
languageCode = "en-us"
theme = "cactus"
title = "Nathan Chancellor"

[author]
  name = "Nathan Chancellor"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
    weight     = 1
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 2
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/nc_resume.pdf"
    weight     = 3
  [[menu.main]]
    identifier = "downloads"
    name       = "Downloads"
    url        = "/downloads"
    weight     = 4

# Theme specific configuration
[params]
  description = "I am a Linux kernel developer focused on improving compatibility with LLVM and clang as part of [ClangBuiltLinux](https://clangbuiltlinux.github.io/). I mostly blog about my work and tips and tricks that I discover."
  mainSection = "posts"
  mainSectionTitle = "Blog"
  projectsUrl = "https://github.com/nathanchance"
  showAllPostsArchive = true
  showProjectsList = true

  [params.comments]
    enabled = true

  [[params.social]]
    name = "email"
    link  = "nathan@kernel.org"

  [[params.social]]
    name = "github"
    link  = "https://github.com/nathanchance"

  [[params.social]]
    name = "gitlab"
    link  = "https://gitlab.com/nathanchance"

  [[params.social]]
    name = "expeditedssl"
    link  = "/99739260CB6CB716.asc"

  [[params.social]]
    name = "instagram"
    link  = "https://instagram.com/nchancellor"

  [[params.social]]
    name = "linkedin"
    link  = "https://linkedin.com/in/nathanchancellor"

  [[params.social]]
    name = "telegram"
    link  = "https://t.me/nathanchance"

  [[params.social]]
    name = "twitch"
    link  = "https://twitch.tv/nathanchance"

  [[params.social]]
    name = "twitter"
    link  = "https://twitter.com/nathanchance"

  [[params.social]]
    name = "youtube"
    link  = "https://www.youtube.com/user/NateChs"
